# Generated by Django 4.0.6 on 2022-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('openid', models.CharField(max_length=64, unique=True)),
                ('unionId', models.CharField(max_length=64, unique=True)),
                ('nickname', models.CharField(max_length=64)),
                ('headImgUrl', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
